[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
unfocus = "hide"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.linear]
animation = "fromRight"
class = "chrome-linear.app__userevidence_my-issues_assigned-Default"
command = "google-chrome-stable --app=https://linear.app/userevidence/my-issues/assigned"
size = "50% 90%"
lazy = false
unfocus = "hide"
process_tracking = false

[scratchpads.slack]
animation = "fromBottom"
class = "Slack"
command = "/usr/bin/slack --disable-gpu-compositing --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer --enable-features=WaylandWindowDecorations -s %U"
size = "70% 90%"
lazy = false
process_tracking = false
